/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    '6.17': typeof import('./src/components/virtual-waterfall/6.17.vue')['default']
    '旧代码': typeof import('./src/components/virtual-waterfall/旧代码.vue')['default']
    ComponentWrapper: typeof import('./src/components/component-wrapper/component-wrapper.vue')['default']
    copy: typeof import('./src/components/virtual-waterfall/virtual-waterfall copy.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTag: typeof import('element-plus/es')['ElTag']
    FlipCard: typeof import('./src/components/flip-card/flip-card.vue')['default']
    ImgHosting: typeof import('./src/components/img-hosting/img-hosting.vue')['default']
    ImgHosting_old: typeof import('./src/components/img-hosting/img-hosting_old.vue')['default']
    ISvg: typeof import('./src/components/i-svg/i-svg.vue')['default']
    ListPanel: typeof import('./src/components/list-panel/list-panel.vue')['default']
    LocalPicList: typeof import('./src/components/local-pic-list/local-pic-list.vue')['default']
    ModalVirtualWaterfall: typeof import('./src/components/virtual-waterfall-cursor/modal-virtual-waterfall.vue')['default']
    Navigationbar: typeof import('./src/components/navigationbar/navigationbar.vue')['default']
    ProgressiveImage: typeof import('./src/components/progressive-image/progressive-image.vue')['default']
    'ProgressiveImage copy': typeof import('./src/components/progressive-image/progressive-image copy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/search-bar/search-bar.vue')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
    VirtualWaterfall: typeof import('./src/components/virtual-waterfall/virtual-waterfall.vue')['default']
    'VirtualWaterfall copy': typeof import('./src/components/virtual-waterfall/virtual-waterfall copy.vue')['default']
    VirtualWaterfallCursor: typeof import('./src/components/virtual-waterfall-cursor/virtual-waterfall-cursor.vue')['default']
  }
}
